"""empty message

Revision ID: b81da65a3f84
Revises: 855908cbdb04
Create Date: 2019-08-10 19:51:44.851517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b81da65a3f84'
down_revision = '855908cbdb04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('events_location_key', 'events', type_='unique')
    op.drop_constraint('events_title_key', 'events', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('events_title_key', 'events', ['title'])
    op.create_unique_constraint('events_location_key', 'events', ['location'])
    # ### end Alembic commands ###
